### ISSUE TITLE
[Jetton]: Issue:  BocException Error When Calling StableJettonMinter.fromAddress

### ISSUE THREAD

**Issue by nqmgaming** [mrtnetwork/ton_dart#3]
**Error Description:**

Encountered a `BocException` with the message:  
`index is out of bounds index: 327, length: 327`

**Problematic Code:**
```dart
final jettonWallet = await StableJettonMinter.fromAddress(
    owner: wallet.wallet, address: jetton.address, rpc: wallet.rpc);
print("jettonWallettttt: ${jettonWallet}");
```

**Related URL:**  
[https://testnet.tonapi.io/v2/blockchain/accounts/EQAwjrXUd-omirqRRA464jNzkA5pfnxo1RiX3LzDhIr5zhnX](https://testnet.tonapi.io/v2/blockchain/accounts/EQAwjrXUd-omirqRRA464jNzkA5pfnxo1RiX3LzDhIr5zhnX)

**Stack trace:**
```text
Unhandled exception: BocException(index is out of bounds index: 327, length: 327)
#0      BitString.at (package:ton_dart/src/boc/bit/bit_string.dart:56:7)
#1      BitReader._preloadUint (package:ton_dart/src/boc/bit/bit_reader.dart:278:17)
#2      BitReader.preloadUint (package:ton_dart/src/boc/bit/bit_reader.dart:97:12)
#3      BitReader.loadMaybeAddress (package:ton_dart/src/boc/bit/bit_reader.dart:189:16)
#4      Slice.loadMaybeAddress (package:ton_dart/src/boc/cell/slice.dart:383:20)
#5      StableTokenMinterState.deserialize (package:ton_dart/src/contracts/token/ft/types/state/stable_minter.dart:66:48)
#6      StableJettonMinter.fromAddress (package:ton_dart/src/contracts/token/ft/contract/minter/stable.dart:45:32)
```

**Comment by nqmgaming** [comment]
### **Additional Question for the Issue:**

How can I retrieve a specific Jetton wallet? The current code uses the following function to get the Jetton for sending:

```dart
final stableJetton = StableJettonMinter.create(
    owner: wallet.wallet,
    state: StableTokenMinterState(
        adminAddress: wallet.address,
        metadata: JettonOffChainMetadata(
            "https://raw.githubusercontent.com/mrtnetwork/ton_dart/d033738c5aad3877ccdd4fa7f570cad5fe46de7b/example/metadata.json")));
```

I’m unclear about how this function works. Could you provide an explanation?

**Comment by mrtnetwork** [comment]
> ### **Additional Question for the Issue:**
> How can I retrieve a specific Jetton wallet? The current code uses the following function to get the Jetton for sending:
> 
> ```dart
> final stableJetton = StableJettonMinter.create(
>     owner: wallet.wallet,
>     state: StableTokenMinterState(
>         adminAddress: wallet.address,
>         metadata: JettonOffChainMetadata(
>             "https://raw.githubusercontent.com/mrtnetwork/ton_dart/d033738c5aad3877ccdd4fa7f570cad5fe46de7b/example/metadata.json")));
> ```
> 
> I’m unclear about how this function works. Could you provide an explanation?

you can get Jetton wallet like

```
// Example: Jetton Minter
final jettonMinter = StableJettonMinter(
  address: TonAddress("kQAwjrXUd-omirqRRA464jNzkA5pfnxo1RiX3LzDhIr5zqJd"), // Replace with the Jetton Minter address
  owner: wallet.wallet, // Your wallet instance
  state: null, // Provide state if necessary
);

// Get the Jetton Wallet contract associated with the Minter
final jettonWallet = await jettonMinter.getJettonWalletContract(
  rpc: wallet.rpc, // Provide your RPC client instance
  owner: wallet.wallet, // Specify the owner's wallet
);

// Alternatively, create a Jetton Wallet directly from its address
final jettonWallet = StableJettonWallet.fromAddress(
  address: address, // Replace with the specific Jetton Wallet address
  owner: owner, // The owner's wallet
  rpc: rpc, // Your RPC client instance
);
```
Once you've obtained the jettonWallet, you can follow the [example](https://github.com/mrtnetwork/ton_dart/blob/main/example/lib/examples/jetton/stable_minter/transfer.dart) starting from line 20 to learn how to send tokens.

You appear to be using a mainnet address on a testnet. While this works in many cases, some contracts might fail.

**Comment by hiennw** [comment]
> > ### **Additional Question for the Issue:**
> > How can I retrieve a specific Jetton wallet? The current code uses the following function to get the Jetton for sending:
> > ```dart
> > final stableJetton = StableJettonMinter.create(
> >     owner: wallet.wallet,
> >     state: StableTokenMinterState(
> >         adminAddress: wallet.address,
> >         metadata: JettonOffChainMetadata(
> >             "https://raw.githubusercontent.com/mrtnetwork/ton_dart/d033738c5aad3877ccdd4fa7f570cad5fe46de7b/example/metadata.json")));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I’m unclear about how this function works. Could you provide an explanation?
> 
> you can get Jetton wallet like
> 
> ```
> // Example: Jetton Minter
> final jettonMinter = StableJettonMinter(
>   address: TonAddress("kQAwjrXUd-omirqRRA464jNzkA5pfnxo1RiX3LzDhIr5zqJd"), // Replace with the Jetton Minter address
>   owner: wallet.wallet, // Your wallet instance
>   state: null, // Provide state if necessary
> );
> 
> // Get the Jetton Wallet contract associated with the Minter
> final jettonWallet = await jettonMinter.getJettonWalletContract(
>   rpc: wallet.rpc, // Provide your RPC client instance
>   owner: wallet.wallet, // Specify the owner's wallet
> );
> 
> // Alternatively, create a Jetton Wallet directly from its address
> final jettonWallet = StableJettonWallet.fromAddress(
>   address: address, // Replace with the specific Jetton Wallet address
>   owner: owner, // The owner's wallet
>   rpc: rpc, // Your RPC client instance
> );
> ```
> 
> Once you've obtained the jettonWallet, you can follow the [example](https://github.com/mrtnetwork/ton_dart/blob/main/example/lib/examples/jetton/stable_minter/transfer.dart) starting from line 20 to learn how to send tokens.
> 
> You appear to be using a mainnet address on a testnet. While this works in many cases, some contracts might fail.


@mrtnetwork I tried the above code, but it returned the following error.:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: TonContractException(Invalid stable token wallet status. tag: 10, availableTags: 0, 1, 2, 3)
#0      StableTokenWalletStatus.fromTag.<anonymous closure> (package:ton_dart/src/contracts/token/ft/types/state/stable_wallet.dart:32:21)
#1      ListBase.firstWhere (dart:collection/list.dart:131:38)
#2      StableTokenWalletStatus.fromTag (package:ton_dart/src/contracts/token/ft/types/state/stable_wallet.dart:30:19)
#3      new StableJettonWalletState.deserialize (package:ton_dart/src/contracts/token/ft/types/state/stable_wallet.dart:104:41)
#4      StableJettonWallet.fromAddress (package:ton_dart/src/contracts/token/ft/contract/wallet/stable_jetton_wallet.dart:30:33)
```
